### ISSUE TITLE
How to set author name in commit

### ISSUE THREAD

**Issue by tadeankur** [fitnesse/fitnesse-git-plugin#10]
Hello , 

When git plugin commits the pages it doesn't uses the default author name from git global setting
I was wondering about is there any configuration parameter needs to be provided to set the author to the commit ?

Regards

Ankur

**Comment by JThoennes** [comment]
This also cause issues on rebase because git does not like the empty committer id.

**Comment by CaBocuk** [comment]
have the same issue now. @tadeankur have you overcome it finally?
