### ISSUE TITLE
Need documentation

### ISSUE THREAD

**Issue by mickaeltr** [fitnesse/fitnesse-git-plugin#3]
Hello,
I would like to know more about how this plugin works:

- Which files must be under version control ?
- Will FitNesse push automatically the changes made in the Git repository?
- Will FitNesse pull automatically the changes made in the Git repository? (otherwise is there any way to do that)
- What happens in case of merge conflict?

Thanks a lot

**Comment by mickaeltr** [comment]
By playing with it, I pretty much answered all my questions:


- Which files must be under version control ?
=> The whole FitNesseRoot must be the root of the Git repo.

- Will FitNesse push automatically the changes made in the Git repository?
=> No

- Will FitNesse pull automatically the changes made in the Git repository?
=> No

**Comment by binkley** [comment]
Agree on documentation.  Thank you for answering questions inline.  More in the `README.md` would be helpful.  For example, what are the properties I can use to configure the plugin?

**Comment by amolenaar** [comment]
I updated the readme some time back. Did I miss anything?

**Comment by mickaeltr** [comment]
That's fine. Thank you very much for the documentation effort.
I'll let @binkley share his mind before closing the issue.

**Comment by binkley** [comment]
Hey, @mickaeltr, README looks good.  A pity about not having more control on commit message, or pushing, but those are features, not doc changes.  :-)
